# Generated by Django 4.1.2 on 2022-12-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_teacher_detail_alter_course_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name_plural": "1. Teachers"},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="qualification",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="video_duration",
        ),
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="mobile_no",
        ),
    ]
