# Generated by Django 4.1.2 on 2022-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
