# Generated by Django 4.1.2 on 2022-12-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_teacher_detail_teacher_profile_img_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courserating",
            options={"verbose_name_plural": "8. Course Ratings"},
        ),
        migrations.CreateModel(
            name="StudentFavoriteCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "7. Student Favorite Courses",
            },
        ),
    ]
